export const language = {
    en: {
        home: "home",
        contact: "contact",
        login: "login",
        name: "name",
        email: "email",
        phonenumber: "phone number",
        country: "country",
        text: "text",
        nameEnterMessage: "enter name",
        emailEnterMessage: "enter email",
        phoneNumberEnterMessage: "enter phone number",
        countryEnterMessage: "pick a country",
        textEnterMessage: "enter text",
        submit: "submit",
        noitems: "no items",
        password: "password",
        cancel: "cancel",
        tr: "Turkey",
        tur: "Turkish",
        en: "English",
        us: "United States of America",
        uk: "United Kingdom",
        de: "Germany",
        se: "Sweden",
        ke: "Kenya",
        br: "Brazil",
        zw: "Zimbabwe",
    },
    tr: {
        home: "anasayfa",
        contact: "iletişim",
        login: "giriş yap",
        name: "isim",
        email: "e-posta",
        phonenumber: "telefon numarası",
        country: "ülke",
        text: "mesaj",
        nameEnterMessage: "isim giriniz",
        emailEnterMessage: "e-posta giriniz",
        phoneNumberEnterMessage: "telefon numarası giriniz",
        countryEnterMessage: "ülke seçin",
        textEnterMessage: "mesaj yazın",
        submit: "gönder",
        noitems: "öğe yok",
        password: "parola",
        cancel: "iptal",
        tr: "Türkiye",
        tur: "Türkçe",
        en: "İngilizce",
        us: "Amerika Birleşik Devletleri",
        uk: "Birleşik Krallık",
        de: "Almanya",
        se: "İsviçre",
        ke: "Kenya",
        br: "Brezilya",
        zw: "Zimbabve",
    }
}